version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: rails_wave
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
